---
 - hosts: local
   gather_facts: true
   tasks:
    - block:
      - name: Installing httpd for Redhat
        yum:
         name: httpd
         state: present
      - name: Starting the service
        service:
         name: httpd
         state: started
      when: ansible_os_family=="RedHat"
      become: yes
    - debug:
       msg: "Successfully Installed httpd packge on {{inventory_hostname}}"
     
