---
 - name: Line change ex.2
   hosts: local
   become: true
   tasks:
    - name: To insert a line before
      lineinfile:
       dest: /root/files/file1.txt
       line: '^4.'
       state: absent
